// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class CouponPic
{
    public int? CouponID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int CouponPicID { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("CouponPics")]
    public virtual Coupon Coupon { get; set; }
}