// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Index("CouponCode", Name = "UQ__Coupons__D349080054BB6769", IsUnique = true)]
public partial class Coupon
{
    [Key]
    public int CouponID { get; set; }

    [StringLength(50)]
    public string CouponCode { get; set; }

    public string CouponDesc { get; set; }

    public int? DiscountType { get; set; }

    [Column(TypeName = "numeric(7, 2)")]
    public decimal? DiscountValue { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsActive { get; set; }

    [StringLength(50)]
    public string DiscountCode { get; set; }

    [InverseProperty("Coupon")]
    public virtual ICollection<CouponPic> CouponPics { get; set; } = new List<CouponPic>();

    [InverseProperty("Coupon")]
    public virtual ICollection<Coupon_CustomerLevel> Coupon_CustomerLevels { get; set; } = new List<Coupon_CustomerLevel>();
}