// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Coupon_CustomerLevel
{
    [Key]
    public int CouponLevelID { get; set; }

    public int? CouponID { get; set; }

    public int? CustomerLevel { get; set; }

    [ForeignKey("CouponID")]
    [InverseProperty("Coupon_CustomerLevels")]
    public virtual Coupon Coupon { get; set; }
}