// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("CustomerBlacklist")]
public partial class CustomerBlacklist
{
    [Key]
    public int BlacklistID { get; set; }

    public int? CustomerID { get; set; }

    public string Reason { get; set; }

    public DateTime? CreateTime { get; set; }

    public int? PermissionStatus { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerBlacklists")]
    public virtual CustomerProfile Customer { get; set; }
}