// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Keyless]
public partial class CustomerCouponsRecord
{
    public int? CustomerID { get; set; }

    public int? CouponID { get; set; }

    public bool? IsUsed { get; set; }

    public DateTime? UsedTime { get; set; }

    [ForeignKey("CouponID")]
    public virtual Coupon Coupon { get; set; }

    [ForeignKey("CustomerID")]
    public virtual Customer Customer { get; set; }
}