// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("CustomerSupportFeedback")]
public partial class CustomerSupportFeedback
{
    [Key]
    public int FeedbackID { get; set; }

    public int? TicketID { get; set; }

    public int? CustomerID { get; set; }

    public int? FeedbackRating { get; set; }

    public string FeedbackComment { get; set; }

    public DateTime? CreateTime { get; set; }

    [ForeignKey("TicketID")]
    [InverseProperty("CustomerSupportFeedbacks")]
    public virtual CustomerSupportTicket Ticket { get; set; }
}