// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("CustomerProfile")]
[Index("CustomerID", Name = "UQ__Customer__A4AE64B9116BDBAC", IsUnique = true)]
public partial class CustomerProfile
{
    [Key]
    public int CustomerProfilesID { get; set; }

    [Required]
    public int? CustomerID { get; set; }

    [StringLength(50)]
    public string CustomerName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string IDNumber { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string CustomerProfileCode { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerProfile")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerBlacklist> CustomerBlacklists { get; set; } = new List<CustomerBlacklist>();

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerOrder> CustomerOrders { get; set; } = new List<CustomerOrder>();

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerSupportTicket> CustomerSupportTickets { get; set; } = new List<CustomerSupportTicket>();
}