// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class CustomerSupportMessage
{
    [Key]
    public int MessageID { get; set; }

    public int? TicketID { get; set; }

    public int? SenderID { get; set; }

    public int? ReceiverID { get; set; }

    public string MessageContent { get; set; }

    public int? UnreadCount { get; set; }

    [StringLength(500)]
    public string AttachmentURL { get; set; }

    public DateTime? SentTime { get; set; }

    [ForeignKey("TicketID")]
    [InverseProperty("CustomerSupportMessages")]
    public virtual CustomerSupportTicket Ticket { get; set; }
}