// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class CustomerOrder
{
    public int? CustomerID { get; set; }

    public int? ProductID { get; set; }

    [Key]
    public int OrderID { get; set; }

    public int? OrderStatusID { get; set; }

    public int? TotalAmount { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerOrders")]
    public virtual CustomerProfile Customer { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<CustomerOrderFeedback> CustomerOrderFeedbacks { get; set; } = new List<CustomerOrderFeedback>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderPaymentInfo> OrderPaymentInfos { get; set; } = new List<OrderPaymentInfo>();

    [ForeignKey("OrderStatusID")]
    [InverseProperty("CustomerOrders")]
    public virtual OrderStatus OrderStatus { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("CustomerOrders")]
    public virtual Product Product { get; set; }
}