// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Keyless]
[Table("CustomerOrderMemberInfo")]
public partial class CustomerOrderMemberInfo
{
    public int? OrderID { get; set; }

    [StringLength(50)]
    public string CustomerName { get; set; }

    [StringLength(20)]
    public string IDNumber { get; set; }

    public DateTime? CustomerBirth { get; set; }

    [ForeignKey("OrderID")]
    public virtual CustomerOrder Order { get; set; }
}