// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("CustomerOrderFeedback")]
public partial class CustomerOrderFeedback
{
    [Key]
    public int FeedbackID { get; set; }

    public int? OrderID { get; set; }

    public int? CustomerID { get; set; }

    public int? FeedbackRating { get; set; }

    public string FeedbackComment { get; set; }

    public DateTime? CreateTime { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("CustomerOrderFeedbacks")]
    public virtual CustomerOrder Order { get; set; }
}