// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("CustomerLoginHistory")]
public partial class CustomerLoginHistory
{
    public int? CustomerID { get; set; }

    [StringLength(45)]
    public string LoginIP { get; set; }

    public DateTime? LoginTime { get; set; }

    public bool? IsSuccessful { get; set; }

    [Key]
    public int LoginLogID { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerLoginHistories")]
    public virtual Customer Customer { get; set; }
}