// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Index("Account", Name = "UQ__Customer__B0C3AC46F6875C6D", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int CustomerID { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(200)]
    public string Password { get; set; }

    [StringLength(20)]
    public string FullName { get; set; }

    public int? Level { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? Status { get; set; }

    public bool? IsBlacklisted { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string CustomerCode { get; set; }

    public string UserId { get; set; }

    public DateTime? LevelUpdatedAt { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerLoginHistory> CustomerLoginHistories { get; set; } = new List<CustomerLoginHistory>();

    [InverseProperty("Customer")]
    public virtual CustomerProfile CustomerProfile { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerTripProject> CustomerTripProjects { get; set; } = new List<CustomerTripProject>();

    [ForeignKey("Level")]
    [InverseProperty("Customers")]
    public virtual CustomerLevel LevelNavigation { get; set; }
}