// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class CustomerTripProject
{
    public int? CustomerID { get; set; }

    [Key]
    public int ProjectID { get; set; }

    [StringLength(100)]
    public string ProjectName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerTripProjects")]
    public virtual Customer Customer { get; set; }
}