// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class CustomerSupportTicket
{
    [Key]
    public int TicketID { get; set; }

    public int? CustomerID { get; set; }

    public int? EmployeeID { get; set; }

    [Required]
    [StringLength(200)]
    public string Subject { get; set; }

    public int? TicketTypeID { get; set; }

    public string Description { get; set; }

    public int? StatusID { get; set; }

    public int? PriorityID { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    [StringLength(20)]
    public string TicketCode { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerSupportTickets")]
    public virtual CustomerProfile Customer { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<CustomerSupportFeedback> CustomerSupportFeedbacks { get; set; } = new List<CustomerSupportFeedback>();

    [InverseProperty("Ticket")]
    public virtual ICollection<CustomerSupportMessage> CustomerSupportMessages { get; set; } = new List<CustomerSupportMessage>();

    [ForeignKey("EmployeeID")]
    [InverseProperty("CustomerSupportTickets")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("PriorityID")]
    [InverseProperty("CustomerSupportTickets")]
    public virtual TicketPriority Priority { get; set; }

    [ForeignKey("StatusID")]
    [InverseProperty("CustomerSupportTickets")]
    public virtual TicketStatus Status { get; set; }

    [ForeignKey("TicketTypeID")]
    [InverseProperty("CustomerSupportTickets")]
    public virtual TicketType TicketType { get; set; }
}