// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("DateDimension")]
public partial class DateDimension
{
    [Key]
    public int DateID { get; set; }

    public DateTime? Date { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

    public int? Day { get; set; }

    public int? Week { get; set; }

    public int? DayOfWeek { get; set; }

    [StringLength(10)]
    public string DayName { get; set; }

    public bool? IsWeekend { get; set; }

    public bool? IsHoliday { get; set; }
}