// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class District
{
    [Key]
    public int DistrictID { get; set; }

    [StringLength(20)]
    public string DistrictName { get; set; }

    [InverseProperty("District")]
    public virtual ICollection<Hotel> Hotels { get; set; } = new List<Hotel>();

    [InverseProperty("District")]
    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    [InverseProperty("District")]
    public virtual ICollection<Restaurant> Restaurants { get; set; } = new List<Restaurant>();
}