// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("EmployeeProfile")]
[Index("EmployeeID", Name = "UQ__Employee__7AD04FF0BADC7135", IsUnique = true)]
public partial class EmployeeProfile
{
    [Key]
    public int EmployeeProfileID { get; set; }

    [Required]
    public int? EmployeeID { get; set; }

    [StringLength(50)]
    public string EmployeeName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string IDNumber { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    public byte[] Photo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeProfileCode { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("EmployeeProfile")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<NewsTable> NewsTables { get; set; } = new List<NewsTable>();
}