// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Index("Account", Name = "UQ__Employee__B0C3AC465D815FE8", IsUnique = true)]
public partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(200)]
    public string Password { get; set; }

    public int? RoleID { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? Status { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmployeeCode { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<CustomerSupportTicket> CustomerSupportTickets { get; set; } = new List<CustomerSupportTicket>();

    [InverseProperty("Employee")]
    public virtual EmployeeProfile EmployeeProfile { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("Employees")]
    public virtual EmployeeRole Role { get; set; }
}