// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class FAQ
{
    [Key]
    public int FAQID { get; set; }

    [StringLength(200)]
    public string Question { get; set; }

    public string Answer { get; set; }

    public int? CategoryID { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public bool? IsActive { get; set; }

    public bool IsHot { get; set; }

    public int HotOrder { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("FAQs")]
    public virtual FAQCategory Category { get; set; }
}