// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class FAQCategory
{
    [Key]
    public int CategoryID { get; set; }

    [StringLength(200)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<FAQ> FAQs { get; set; } = new List<FAQ>();
}