// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class GroupLocation
{
    [Key]
    public int LocationId { get; set; }

    public int GroupId { get; set; }

    [StringLength(10)]
    public string SenderType { get; set; }

    public int? GuideId { get; set; }

    [StringLength(450)]
    public string CustomerId { get; set; }

    public Guid? GuestId { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Longitude { get; set; }

    public DateTime? RecordTime { get; set; }

    [StringLength(100)]
    public string Note { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("GroupLocations")]
    public virtual TourGroup Group { get; set; }
}