// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class GroupMessage
{
    [Key]
    public int MessageId { get; set; }

    public int GroupId { get; set; }

    [StringLength(10)]
    public string SenderType { get; set; }

    [StringLength(450)]
    public string CustomerId { get; set; }

    public Guid? GuestId { get; set; }

    public int? GuideId { get; set; }

    public string Content { get; set; }

    public DateTime? SendTime { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("GroupMessages")]
    public virtual TourGroup Group { get; set; }
}