// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class GroupPhoto
{
    [Key]
    public int PhotoId { get; set; }

    public int GroupId { get; set; }

    [StringLength(10)]
    public string UploaderType { get; set; }

    [StringLength(450)]
    public string CustomerId { get; set; }

    public Guid? GuestId { get; set; }

    public int? GuideId { get; set; }

    [StringLength(255)]
    public string FilePath { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Longitude { get; set; }

    public DateTime? UploadTime { get; set; }

    public bool? IsApproved { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("GroupPhotos")]
    public virtual TourGroup Group { get; set; }
}