// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class HotelKeyword
{
    public int? HotelID { get; set; }

    public int? KeywordID { get; set; }

    [Key]
    public int HotelKeywordID { get; set; }

    [ForeignKey("HotelID")]
    [InverseProperty("HotelKeywords")]
    public virtual Hotel Hotel { get; set; }

    [ForeignKey("KeywordID")]
    [InverseProperty("HotelKeywords")]
    public virtual Keyword Keyword { get; set; }
}