// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Hotel
{
    [Key]
    public int HotelID { get; set; }

    [StringLength(200)]
    public string HotelName { get; set; }

    [StringLength(200)]
    public string HotelAddr { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? HotelLat { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? HotelLng { get; set; }

    public string HotelDesc { get; set; }

    public int? RegionID { get; set; }

    public int? DistrictID { get; set; }

    [Column(TypeName = "numeric(2, 1)")]
    public decimal? Rating { get; set; }

    public int? Views { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string HotelCode { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("DistrictID")]
    [InverseProperty("Hotels")]
    public virtual District District { get; set; }

    [InverseProperty("Hotel")]
    public virtual ICollection<HotelKeyword> HotelKeywords { get; set; } = new List<HotelKeyword>();

    [InverseProperty("Hotel")]
    public virtual ICollection<HotelPic> HotelPics { get; set; } = new List<HotelPic>();

    [InverseProperty("Hotel")]
    public virtual ICollection<Products_Hotel> Products_Hotels { get; set; } = new List<Products_Hotel>();

    [ForeignKey("RegionID")]
    [InverseProperty("Hotels")]
    public virtual Region Region { get; set; }

    [InverseProperty("Hotel")]
    public virtual ICollection<Semi_Hotel> Semi_Hotels { get; set; } = new List<Semi_Hotel>();
}