// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class HotelPic
{
    public int? HotelID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int HotelPicID { get; set; }

    [ForeignKey("HotelID")]
    [InverseProperty("HotelPics")]
    public virtual Hotel Hotel { get; set; }
}