// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Keyword
{
    [Column("Keyword")]
    [StringLength(15)]
    public string Keyword1 { get; set; }

    public int? Views { get; set; }

    [Key]
    public int KeywordID { get; set; }

    [InverseProperty("Keyword")]
    public virtual ICollection<HotelKeyword> HotelKeywords { get; set; } = new List<HotelKeyword>();

    [InverseProperty("Keyword")]
    public virtual ICollection<LocationKeyword> LocationKeywords { get; set; } = new List<LocationKeyword>();

    [InverseProperty("Keyword")]
    public virtual ICollection<RestaurantKeyword> RestaurantKeywords { get; set; } = new List<RestaurantKeyword>();

    [InverseProperty("Keyword")]
    public virtual ICollection<TransportKeyword> TransportKeywords { get; set; } = new List<TransportKeyword>();
}