// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Location
{
    [Key]
    public int LocationID { get; set; }

    [StringLength(50)]
    public string LocationName { get; set; }

    [StringLength(200)]
    public string LocationAddr { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? LocationLat { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? LocationLng { get; set; }

    public string LocationDesc { get; set; }

    public int? LocationPrice { get; set; }

    public int? RegionID { get; set; }

    public int? DistrictID { get; set; }

    [Column(TypeName = "numeric(2, 1)")]
    public decimal? Rating { get; set; }

    public int? Views { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string LocationCode { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("DistrictID")]
    [InverseProperty("Locations")]
    public virtual District District { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<LocationKeyword> LocationKeywords { get; set; } = new List<LocationKeyword>();

    [InverseProperty("Location")]
    public virtual ICollection<LocationPic> LocationPics { get; set; } = new List<LocationPic>();

    [InverseProperty("Location")]
    public virtual ICollection<Products_Location> Products_Locations { get; set; } = new List<Products_Location>();

    [ForeignKey("RegionID")]
    [InverseProperty("Locations")]
    public virtual Region Region { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<Semi_Location> Semi_Locations { get; set; } = new List<Semi_Location>();
}