// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class LocationKeyword
{
    public int? LocationID { get; set; }

    public int? KeywordID { get; set; }

    [Key]
    public int LocationKeywordID { get; set; }

    [ForeignKey("KeywordID")]
    [InverseProperty("LocationKeywords")]
    public virtual Keyword Keyword { get; set; }

    [ForeignKey("LocationID")]
    [InverseProperty("LocationKeywords")]
    public virtual Location Location { get; set; }
}