// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class LocationPic
{
    public int? LocationID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int LocationPicID { get; set; }

    [ForeignKey("LocationID")]
    [InverseProperty("LocationPics")]
    public virtual Location Location { get; set; }
}