// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class NewsPic
{
    public int? NewsID { get; set; }

    [Column("NewsPic")]
    public byte[] NewsPic1 { get; set; }

    [Key]
    public int NewsPicID { get; set; }

    [ForeignKey("NewsID")]
    [InverseProperty("NewsPics")]
    public virtual NewsTable News { get; set; }
}