// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("NewsTable")]
public partial class NewsTable
{
    [Key]
    public int NewsID { get; set; }

    [StringLength(200)]
    public string NewsTitle { get; set; }

    public string NewsContent { get; set; }

    public DateTime? PublishTime { get; set; }

    public DateTime? ExpireTime { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public int? EmployeeID { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("NewsTables")]
    public virtual EmployeeProfile Employee { get; set; }

    [InverseProperty("News")]
    public virtual ICollection<NewsPic> NewsPics { get; set; } = new List<NewsPic>();
}