// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("OrderStatus")]
public partial class OrderStatus
{
    [Key]
    public int OrderStatusID { get; set; }

    [StringLength(50)]
    public string StatusDesc { get; set; }

    [InverseProperty("OrderStatus")]
    public virtual ICollection<CustomerOrder> CustomerOrders { get; set; } = new List<CustomerOrder>();
}