// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("OrderPaymentInfo")]
public partial class OrderPaymentInfo
{
    [Key]
    public int PaymentID { get; set; }

    public int? OrderID { get; set; }

    public int? PaymentAmount { get; set; }

    public int? PaymentStatusID { get; set; }

    public DateTime? TransectionTime { get; set; }

    public string Notes { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("OrderPaymentInfos")]
    public virtual CustomerOrder Order { get; set; }

    [ForeignKey("PaymentStatusID")]
    [InverseProperty("OrderPaymentInfos")]
    public virtual PaymentStatus PaymentStatus { get; set; }
}