// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("PaymentStatus")]
public partial class PaymentStatus
{
    [Key]
    public int PayMentStatusID { get; set; }

    [StringLength(50)]
    public string StatusDesc { get; set; }

    [InverseProperty("PaymentStatus")]
    public virtual ICollection<OrderPaymentInfo> OrderPaymentInfos { get; set; } = new List<OrderPaymentInfo>();
}