// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Products_Promotion
{
    public int? PromoID { get; set; }

    public int? ProductID { get; set; }

    [Key]
    public int ProductPromoID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Products_Promotions")]
    public virtual Product Product { get; set; }

    [ForeignKey("PromoID")]
    [InverseProperty("Products_Promotions")]
    public virtual Promotion Promo { get; set; }
}