// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("ProductAnalysis")]
public partial class ProductAnalysis
{
    public int? ProductID { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public DateTime? RemovalDate { get; set; }

    [Key]
    public int ProductAnalysisID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductAnalyses")]
    public virtual Product Product { get; set; }
}