// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class ProductPic
{
    public int? ProductID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int ProductPicID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductPics")]
    public virtual Product Product { get; set; }
}