// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [StringLength(150)]
    public string ProductName { get; set; }

    public int? RegionID { get; set; }

    public string ProductDesc { get; set; }

    public int? ProductPrice { get; set; }

    public string ProductNote { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? MaxPeople { get; set; }

    public byte[] ProductImage { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    public bool? IsActive { get; set; }

    public int? Views { get; set; }

    public DateTime CreateTime { get; set; }

    public string ProductImageUrl { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<CustomerOrder> CustomerOrders { get; set; } = new List<CustomerOrder>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductAnalysis> ProductAnalyses { get; set; } = new List<ProductAnalysis>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductPic> ProductPics { get; set; } = new List<ProductPic>();

    [InverseProperty("Product")]
    public virtual ICollection<Products_Hotel> Products_Hotels { get; set; } = new List<Products_Hotel>();

    [InverseProperty("Product")]
    public virtual ICollection<Products_Location> Products_Locations { get; set; } = new List<Products_Location>();

    [InverseProperty("Product")]
    public virtual ICollection<Products_Promotion> Products_Promotions { get; set; } = new List<Products_Promotion>();

    [InverseProperty("Product")]
    public virtual ICollection<Products_Restaurant> Products_Restaurants { get; set; } = new List<Products_Restaurant>();

    [InverseProperty("Product")]
    public virtual ICollection<Products_Transportation> Products_Transportations { get; set; } = new List<Products_Transportation>();

    [ForeignKey("RegionID")]
    [InverseProperty("Products")]
    public virtual Region Region { get; set; }
}