// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Products_Hotel
{
    public int? ProductID { get; set; }

    public int? HotelID { get; set; }

    [Key]
    public int ProductHotelID { get; set; }

    public int? OrderIndex { get; set; }

    [ForeignKey("HotelID")]
    [InverseProperty("Products_Hotels")]
    public virtual Hotel Hotel { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Products_Hotels")]
    public virtual Product Product { get; set; }
}