// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Products_Transportation
{
    public int? ProductID { get; set; }

    public int? TransportID { get; set; }

    public string TransportInfo { get; set; }

    public DateTime? TransportTime { get; set; }

    [Key]
    public int ProductTransID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Products_Transportations")]
    public virtual Product Product { get; set; }

    [ForeignKey("TransportID")]
    [InverseProperty("Products_Transportations")]
    public virtual Transportation Transport { get; set; }
}