// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Products_Restaurant
{
    public int? ProductID { get; set; }

    public int? RestaurantID { get; set; }

    [Key]
    public int ProductRestaurantID { get; set; }

    public int? OrderIndex { get; set; }

    [StringLength(10)]
    public string MealType { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Products_Restaurants")]
    public virtual Product Product { get; set; }

    [ForeignKey("RestaurantID")]
    [InverseProperty("Products_Restaurants")]
    public virtual Restaurant Restaurant { get; set; }
}