// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Promotion
{
    [Key]
    public int PromoID { get; set; }

    [StringLength(200)]
    public string PromoName { get; set; }

    public string PromoDesc { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? DiscountType { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? DiscountValue { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    [InverseProperty("Promo")]
    public virtual ICollection<Products_Promotion> Products_Promotions { get; set; } = new List<Products_Promotion>();
}