// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Region
{
    [Key]
    public int RegionID { get; set; }

    [StringLength(10)]
    public string RegionName { get; set; }

    [InverseProperty("Region")]
    public virtual ICollection<Hotel> Hotels { get; set; } = new List<Hotel>();

    [InverseProperty("Region")]
    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    [InverseProperty("Region")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("Region")]
    public virtual ICollection<Restaurant> Restaurants { get; set; } = new List<Restaurant>();
}