// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Restaurant
{
    [Key]
    public int RestaurantID { get; set; }

    [StringLength(50)]
    public string RestaurantName { get; set; }

    [StringLength(200)]
    public string RestaurantAddr { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? RestaurantLat { get; set; }

    [Column(TypeName = "numeric(9, 6)")]
    public decimal? RestaurantLng { get; set; }

    public string RestaurantDesc { get; set; }

    public int? RegionID { get; set; }

    public int? DistrictID { get; set; }

    [Column(TypeName = "numeric(2, 1)")]
    public decimal? Rating { get; set; }

    public int? Views { get; set; }

    public bool IsActive { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string RestaurantCode { get; set; }

    [ForeignKey("DistrictID")]
    [InverseProperty("Restaurants")]
    public virtual District District { get; set; }

    [InverseProperty("Restaurant")]
    public virtual ICollection<Products_Restaurant> Products_Restaurants { get; set; } = new List<Products_Restaurant>();

    [ForeignKey("RegionID")]
    [InverseProperty("Restaurants")]
    public virtual Region Region { get; set; }

    [InverseProperty("Restaurant")]
    public virtual ICollection<RestaurantKeyword> RestaurantKeywords { get; set; } = new List<RestaurantKeyword>();

    [InverseProperty("Restaurant")]
    public virtual ICollection<RestaurantPic> RestaurantPics { get; set; } = new List<RestaurantPic>();
}