// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class RestaurantPic
{
    public int? RestaurantID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int RestaurantPicID { get; set; }

    [ForeignKey("RestaurantID")]
    [InverseProperty("RestaurantPics")]
    public virtual Restaurant Restaurant { get; set; }
}