// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class RestaurantKeyword
{
    public int? RestaurantID { get; set; }

    public int? KeywordID { get; set; }

    [Key]
    public int RestaurantKeywordID { get; set; }

    [ForeignKey("KeywordID")]
    [InverseProperty("RestaurantKeywords")]
    public virtual Keyword Keyword { get; set; }

    [ForeignKey("RestaurantID")]
    [InverseProperty("RestaurantKeywords")]
    public virtual Restaurant Restaurant { get; set; }
}