// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Semi_Transportation
{
    public int? ProductID { get; set; }

    public int? TransportID { get; set; }

    [Key]
    public int SemiTransID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Semi_Transportations")]
    public virtual SemiSelfProduct Product { get; set; }

    [ForeignKey("TransportID")]
    [InverseProperty("Semi_Transportations")]
    public virtual Transportation Transport { get; set; }
}