// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Semi_Location
{
    public int? ProductID { get; set; }

    public int? LocationID { get; set; }

    [Key]
    public int SemiLocationID { get; set; }

    [ForeignKey("LocationID")]
    [InverseProperty("Semi_Locations")]
    public virtual Location Location { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Semi_Locations")]
    public virtual SemiSelfProduct Product { get; set; }
}