// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class SemiSelfProduct
{
    [Key]
    public int ProductID { get; set; }

    [StringLength(100)]
    public string ProjectName { get; set; }

    public int? Region { get; set; }

    public string ProductDesc { get; set; }

    public int? ProductPrice { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public string Notes { get; set; }

    public int? MaxPeople { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    public bool? IsActive { get; set; }

    public int? Views { get; set; }

    public int? ProductType { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Semi_Hotel> Semi_Hotels { get; set; } = new List<Semi_Hotel>();

    [InverseProperty("Product")]
    public virtual ICollection<Semi_Location> Semi_Locations { get; set; } = new List<Semi_Location>();

    [InverseProperty("Product")]
    public virtual ICollection<Semi_Transportation> Semi_Transportations { get; set; } = new List<Semi_Transportation>();
}