// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Semi_Hotel
{
    public int? ProductID { get; set; }

    public int? HotelID { get; set; }

    [Key]
    public int SemiHotelID { get; set; }

    [ForeignKey("HotelID")]
    [InverseProperty("Semi_Hotels")]
    public virtual Hotel Hotel { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Semi_Hotels")]
    public virtual SemiSelfProduct Product { get; set; }
}