// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[PrimaryKey("SourceTable", "Prefix", "DateKey")]
[Table("SerialControl")]
public partial class SerialControl
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string SourceTable { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Prefix { get; set; }

    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string DateKey { get; set; }

    public int? LastNumber { get; set; }
}