// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Keyless]
[Table("SupportAnalysis")]
public partial class SupportAnalysis
{
    public int? DateID { get; set; }

    public int? TicketID { get; set; }

    public int? OpenedCount { get; set; }

    public int? ResolvedCount { get; set; }

    public int? RatingAverage { get; set; }

    [StringLength(200)]
    public string TopCategory { get; set; }

    [ForeignKey("DateID")]
    public virtual DateDimension Date { get; set; }

    [ForeignKey("TicketID")]
    public virtual CustomerSupportTicket Ticket { get; set; }
}