// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("TicketPriority")]
public partial class TicketPriority
{
    [Key]
    public int PriorityID { get; set; }

    [StringLength(100)]
    public string PriorityDesc { get; set; }

    [InverseProperty("Priority")]
    public virtual ICollection<CustomerSupportTicket> CustomerSupportTickets { get; set; } = new List<CustomerSupportTicket>();
}