// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Index("GroupCode", Name = "UQ__TourGrou__3B9743808676DE8B", IsUnique = true)]
public partial class TourGroup
{
    [Key]
    public int GroupId { get; set; }

    [Required]
    [StringLength(10)]
    public string GroupCode { get; set; }

    [Required]
    [StringLength(100)]
    public string GroupName { get; set; }

    [StringLength(100)]
    public string Destination { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int GuideId { get; set; }

    public DateTime? CreateTime { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<GroupLocation> GroupLocations { get; set; } = new List<GroupLocation>();

    [InverseProperty("Group")]
    public virtual ICollection<GroupMessage> GroupMessages { get; set; } = new List<GroupMessage>();

    [InverseProperty("Group")]
    public virtual ICollection<GroupPhoto> GroupPhotos { get; set; } = new List<GroupPhoto>();

    [InverseProperty("Group")]
    public virtual ICollection<TourGroupGuest> TourGroupGuests { get; set; } = new List<TourGroupGuest>();

    [InverseProperty("Group")]
    public virtual ICollection<TourGroupMember> TourGroupMembers { get; set; } = new List<TourGroupMember>();
}