// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class TourGroupGuest
{
    [Key]
    public Guid GuestId { get; set; }

    public int GroupId { get; set; }

    [StringLength(50)]
    public string TemporaryName { get; set; }

    [StringLength(100)]
    public string DeviceId { get; set; }

    public DateTime? JoinTime { get; set; }

    public DateTime? LastActive { get; set; }

    public bool? IsMember { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("TourGroupGuests")]
    public virtual TourGroup Group { get; set; }
}