// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[PrimaryKey("GroupId", "CustomerId")]
public partial class TourGroupMember
{
    [Key]
    public int GroupId { get; set; }

    [Key]
    public string CustomerId { get; set; }

    public DateTime? JoinTime { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("TourGroupMembers")]
    public virtual TourGroup Group { get; set; }
}