// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class Transportation
{
    [Key]
    public int TransportID { get; set; }

    [StringLength(30)]
    public string TransportName { get; set; }

    public string TransportDesc { get; set; }

    public int? TransportPrice { get; set; }

    [Column(TypeName = "numeric(2, 1)")]
    public decimal? Rating { get; set; }

    public int? Views { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string TransportCode { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Transport")]
    public virtual ICollection<Products_Transportation> Products_Transportations { get; set; } = new List<Products_Transportation>();

    [InverseProperty("Transport")]
    public virtual ICollection<Semi_Transportation> Semi_Transportations { get; set; } = new List<Semi_Transportation>();

    [InverseProperty("Transport")]
    public virtual ICollection<TransportKeyword> TransportKeywords { get; set; } = new List<TransportKeyword>();

    [InverseProperty("Transport")]
    public virtual ICollection<TransportPic> TransportPics { get; set; } = new List<TransportPic>();
}