// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class TransportKeyword
{
    public int? TransportID { get; set; }

    public int? KeywordID { get; set; }

    [Key]
    public int TransportKeywordID { get; set; }

    [ForeignKey("KeywordID")]
    [InverseProperty("TransportKeywords")]
    public virtual Keyword Keyword { get; set; }

    [ForeignKey("TransportID")]
    [InverseProperty("TransportKeywords")]
    public virtual Transportation Transport { get; set; }
}