// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

public partial class TransportPic
{
    public int? TransportID { get; set; }

    public byte[] Picture { get; set; }

    [Key]
    public int TransportPicID { get; set; }

    [ForeignKey("TransportID")]
    [InverseProperty("TransportPics")]
    public virtual Transportation Transport { get; set; }
}