// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Keyless]
public partial class TripProjectDetail
{
    public int? ProjectID { get; set; }

    public DateTime? TripDate { get; set; }

    public int? TripSequence { get; set; }

    public DateTime? StartTime { get; set; }

    public int? StayMinute { get; set; }

    public int? TransportID { get; set; }

    [StringLength(50)]
    public string TripType { get; set; }

    public int? HotelID { get; set; }

    public int? LocationID { get; set; }

    public int? RestaurantID { get; set; }

    public string Notes { get; set; }

    [ForeignKey("HotelID")]
    public virtual Hotel Hotel { get; set; }

    [ForeignKey("LocationID")]
    public virtual Location Location { get; set; }

    [ForeignKey("ProjectID")]
    public virtual CustomerTripProject Project { get; set; }

    [ForeignKey("RestaurantID")]
    public virtual Restaurant Restaurant { get; set; }

    [ForeignKey("TransportID")]
    public virtual Transportation Transport { get; set; }
}