// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Table("VendorLoginHistory")]
public partial class VendorLoginHistory
{
    [Key]
    public int LoginLogID { get; set; }

    public int VendorID { get; set; }

    [StringLength(45)]
    public string LoginIP { get; set; }

    public DateTime LoginTime { get; set; }

    public bool IsSuccessful { get; set; }

    [ForeignKey("VendorID")]
    [InverseProperty("VendorLoginHistories")]
    public virtual Vendor Vendor { get; set; }
}