// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Models;

[Index("Account", Name = "UQ_Vendors_Account", IsUnique = true)]
[Index("UserId", Name = "UQ_Vendors_UserId", IsUnique = true)]
public partial class Vendor
{
    [Key]
    public int VendorId { get; set; }

    [Required]
    public string UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    [Required]
    [StringLength(100)]
    public string CompanyName { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(50)]
    public string ContactName { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(20)]
    public string TaxId { get; set; }

    public bool Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Vendor")]
    public virtual AspNetUser User { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<VendorLoginHistory> VendorLoginHistories { get; set; } = new List<VendorLoginHistory>();
}